INSERT INTO CURRENCY_EXCHANGE (ID, CURRENCY_FROM, CURRENCY_TO, EXCHANGE_VALUE, ENVIRONMENT) VALUES
(10001,'AUD','INR',25,'' );

INSERT INTO CURRENCY_EXCHANGE (ID, CURRENCY_FROM, CURRENCY_TO, EXCHANGE_VALUE, ENVIRONMENT) VALUES
(10002,'USD','INR',65,'' );

INSERT INTO CURRENCY_EXCHANGE (ID, CURRENCY_FROM, CURRENCY_TO, EXCHANGE_VALUE, ENVIRONMENT) VALUES
(10003,'EUD','INR',75,'' );